version: "3.7"

services:
  app:
    image: node:12-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./:/app

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: overview
    volumes:
      - ./overview-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  overview-data: